// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        int32  `json:"id"`
	AccountID string `json:"account_id"`
	// the password md5
	Password sql.NullString `json:"password"`
	Salt     sql.NullString `json:"salt"`
	// 0 admin 1 student 2 ea
	Role  sql.NullInt32 `json:"role"`
	IsNew sql.NullBool  `json:"is_new"`
}

type Admin struct {
	ID   int32          `json:"id"`
	Name sql.NullString `json:"name"`
}

type Bed struct {
	ID        int32         `json:"id"`
	BedID     sql.NullInt32 `json:"bed_id"`
	RID       sql.NullInt32 `json:"r_id"`
	Available sql.NullBool  `json:"available"`
	Used      sql.NullBool  `json:"used"`
}

type Building struct {
	ID             int32         `json:"id"`
	Type           sql.NullInt32 `json:"type"`
	FemaleNum      sql.NullInt32 `json:"female_num"`
	MaleNum        sql.NullInt32 `json:"male_num"`
	FemaleThisyear sql.NullInt32 `json:"female_thisyear"`
	MaleThisyear   sql.NullInt32 `json:"male_thisyear"`
}

type Ea struct {
	ID   int32          `json:"id"`
	Name sql.NullString `json:"name"`
}

type Entry struct {
	ID         int32          `json:"id"`
	SID        int32          `json:"s_id"`
	BuildingID int32          `json:"building_id"`
	SendTime   time.Time      `json:"send_time"`
	GroupNum   sql.NullInt32  `json:"group_num"`
	Partner1   sql.NullString `json:"partner1"`
	Partner2   sql.NullString `json:"partner2"`
	Partner3   sql.NullString `json:"partner3"`
	Status     sql.NullBool   `json:"status"`
	Errorcode  sql.NullInt32  `json:"errorcode"`
}

type Room struct {
	ID         int32          `json:"id"`
	RoomID     sql.NullString `json:"room_id"`
	BuildingID sql.NullInt32  `json:"building_id"`
	Available  sql.NullBool   `json:"available"`
	Gender     sql.NullInt32  `json:"gender"`
	Num        sql.NullInt32  `json:"num"`
	BadNum     sql.NullInt32  `json:"bad_num"`
	FreeNum    sql.NullInt32  `json:"free_num"`
}

type Student struct {
	ID        int32          `json:"id"`
	Name      sql.NullString `json:"name"`
	StudentID sql.NullString `json:"student_id"`
	Grade     sql.NullInt32  `json:"grade"`
	Gender    sql.NullInt32  `json:"gender"`
	Major     sql.NullInt32  `json:"major"`
	Class     sql.NullString `json:"class"`
	Code      sql.NullString `json:"code"`
	Will      sql.NullBool   `json:"will"`
	Payed     sql.NullBool   `json:"payed"`
	CheckIn   sql.NullBool   `json:"check_in"`
}

type StudentBed struct {
	ID          int32         `json:"id"`
	BID         sql.NullInt32 `json:"b_id"`
	SID         sql.NullInt32 `json:"s_id"`
	Check       sql.NullBool  `json:"check"`
	CheckInYear sql.NullInt32 `json:"check_in_year"`
	LiveYears   sql.NullInt32 `json:"live_years"`
}
